import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Othmen belgacem CV </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Othmen belgacem
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Data Quality | Student 
            </h3>
         
           <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                 <a href="https://www.linkedin.com/in/othmen-belgacem/" target="_blank" rel="noopener noreferrer">
                   <AiFillLinkedin />
                 </a>
            </div>

           
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
          <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            I am a 25-year-old, motivated, and dynamic professional with
             a proactive approach to acquiring new skills. I thrive under pressure, adapting to new situations and challenges. 
            Eager to join an innovative and dynamic team where I can leverage my skills and continue to grow.
            </p>
            <h3 className="text-3xl py-1 dark:text-white ">Work Experience:</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            <h2>December 2021 - Present: Data Quality Technician</h2>
  <p><em>Company:</em> Sartorius Stedim Bioprocess</p>

  <h2>February 2020 - June 2020: End-of-Study Internship</h2>
  <p><em>Project:</em> Implementing a Network Infrastructure Using Windows Server 2016</p>
  <p><em>Company:</em> Computer Center of the Ministry of Finance</p>

  <h2>July 2019 - August 2019: End-of-Year Internship</h2>
  <p><em>Project:</em> Structure of a subscriber line network</p>
  <p><em>Company:</em> Tunisie Telecom</p>
            </p>
              <h3 className="text-3xl py-1 dark:text-white ">Education:</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            <h2>August 2021 - December 2021: Development Training Java/JEE</h2>
  <p><em>Institution:</em> Tunisian-German Chamber of Industry and Commerce / CORP</p>

  <h2>September 2017 - June 2020: Bachelor Degree in Computer Networks</h2>
  <p><em>Speciality:</em> Computer Network Technologies</p>
  <p><em>Institution:</em>  Higher Institute of Computer Science of Kef</p>

  <h2>September 2016 - June 2017: Baccalaureate Degree</h2>
  <p><em>Project:</em> Structure of a subscriber line network</p>
  <p><em>Specialty:</em> Baccalaureate Degree in Technology</p>
            </p>
          </div>
          

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
              Skills:
              </h3>
              <p className="py-2">
              Design skills
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                 Skills :
              </h3>
              <p className="py-2">
                Coding skills
              </p>
              <h4 className="py-4 text-teal-600">Coding Tools I Use</h4>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">C++</p>
              <p className="text-gray-800 py-1">React</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">skills</h3>
              <p className="py-2">
              Administrative skills
              </p>
              <h4 className="py-4 text-teal-600">Administrative Tools I Use</h4>
              <p className="text-gray-800 py-1">SAP ERP</p>
              <p className="text-gray-800 py-1">Microsoft office</p>
              <p className="text-gray-800 py-1">data extraction</p>
              <p className="text-gray-800 py-1">presentation software</p>
            </div>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">skills</h3>
              <p className="py-2">
              
              </p>
              <h2 className="py-4 text-teal-600">Languages:</h2>
            
              <p className="text-gray-800 py-1">Arabic: Native</p>
              <p className="text-gray-800 py-1">French: Fluent</p>
              <p className="text-gray-800 py-1">French: Fluent</p>
            </div>
        </section>
      </main>
    </div>
  );
}